global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "litellm-gateway"
    metrics_path: "/metrics/"
    static_configs:
      - targets: ["litellm:4000"]

  - job_name: "cps-companion"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["cps_webhook:4001"]
